version: '3'

services:
  react-app:
    image: node:14
    working_dir: /app
    volumes:
      - ./react-app:/app
    ports:
      - "3000:3000"
    command: npm start

  nginx:
    image: nginx:latest
    ports:
      - "2080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./react-app/build:/usr/share/nginx/html
    depends_on:
      - react-app

  mongo:
    image: webhippie/mongodb:latest-arm32v7
    volumes:
      - /mnt/usb:/data/db
    ports:
      - "27017:27017"
