version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "2080:80"
    volumes:
      - ./react-app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./react-app/build:/usr/share/nginx/html
    restart: always

  mongo:
    image: webhippie/mongodb:latest-arm32v7
    environment:
      - MONGO_DATA_DIR=/data/db
      # - MONGO_INITDB_ROOT_USERNAME=rootuser
      # - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - ./mongo/mongo.conf:/etc/mongo/mongod.conf
      - /mnt/usb:/data/db
    ports:
      - "27017:27017"

  # mysql:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: brain-dump-db
  #     MYSQL_USER: braindump
  #     MYSQL_PASSWORD: regpass
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - /mnt/usb:/var/lib/mysql

  go-app:
    image: golang:1.17
    working_dir: /go/src/app
    volumes:
      - ./backend/backend-go:/go/src/app/backend-go
    command: ./backend-go
    ports:
      - "2081:2081"
    restart: always
    depends_on:
      - mongo
